### ISSUE TITLE
How did you calculate the values needed for the read/write functions?

### ISSUE THREAD

**Issue by So1idus** [Jayveer/MGS-KMS-EVM-Noesis#2]
I apologize for opening an issue, but could you explain how you calculated the values you passed into the read and write functions? I went as far as to read the GS User Manual and yet I still don't understand.

**Comment by Jayveer** [comment]
That's ok, I'm assuming this is for the textures considering it's to do with GS. It was a while ago when I made this but knowing the arguments to pass to the PS2 Unswizzling code was part trial and error, and part knowledge of how the mgs games generally structure their texture formats. That part will most likely differ for other games as they will have their own custom file formats to describe the layout of the textures.

**Comment by So1idus** [comment]
Yeah, I was talking about the unswizzling code, I see now I could have been clearer. I deeply appreciate the clarification, though I don't look forward to experimenting.
